apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: funixgaming-website-certificate
  namespace: "funixproductions"
spec:
  secretName: funixgaming-website-certificate-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "funixgaming.fr"
  dnsNames:
    - "funixgaming.fr"
